### ISSUE TITLE
老师你好!

### ISSUE THREAD

**Issue by pynne** [redace85/Fcmd#1]
是否可以加上Argparse模块，
这样就可以直接命令行显示了。
比如
python fcmd.py mtk btcusdt

这样比较方便。

**Comment by liuji85** [comment]
> 是否可以加上Argparse模块，
> 这样就可以直接命令行显示了。
> 比如
> python fcmd.py mtk btcusdt
> 
> 这样比较方便。

同学你好！
我不是什么老师，
其次编写fcmd.py主要是为了使用交互式命令行。
要实现单次运行输出到命令行其实更简单，只有调用aiofoin.py里到函数打印返回就行了。

**Comment by redace85** [comment]
> 是否可以加上Argparse模块，
> 这样就可以直接命令行显示了。
> 比如
> python fcmd.py mtk btcusdt
> 
> 这样比较方便。

同学你好！
我不是老师，
编写fcmd.py就是为了使用交互式到命令行。
要实现单次运行输出到命令行，只要调用aiofoin.py里的函数，打印返回就行了

**Comment by pynne** [comment]
博主谦虚了。我是刚刚接触到python 很多地方不太懂。
能写一个例子吗？比如 ：挂 btcusdt ，限价, 数量：交易账户可用金额的50%，
谢谢了。
不知有ft的收款地址吗？
