### ISSUE TITLE
感谢了

### ISSUE THREAD

**Issue by pynne** [redace85/Fcmd#2]
博主谦虚了。我是刚刚接触到python 很多地方不太懂。
在实现单次运行输出到命令行比较没有头绪。
能写一个例子吗？比如 ：挂 btcusdt ，限价, 数量：交易账户可用金额的50%，
谢谢。
不知有ft的收款地址吗？

**Comment by redace85** [comment]
> 博主谦虚了。我是刚刚接触到python 很多地方不太懂。
> 在实现单次运行输出到命令行比较没有头绪。
> 能写一个例子吗？比如 ：挂 btcusdt ，限价, 数量：交易账户可用金额的50%，
> 谢谢。
> 不知有ft的收款地址吗？

同学你好，
issue一般是用于讨论，跟踪程序本身所出现的问题。如果你有其他方面的事情想和我讨论，可以加我的微信，在README下方，捐赠部分。

单次运行输出，简单点说就是类似 打印hello word到命令行。
fcmd 里有个 oc 命令可以创建 买卖单。
ft的收款地址 当然是有的；请问您是想捐赠我ft吗？
